### PR TITLE
Add response as json to callArtisan

### LINKED ISSUE #9: callArtisan to return console output as JSON
In my use case I am running an artisan command, and I would like to get the output of that command to use in my test.

### PR DESCRIPTION
**Pull request by ianjamieson**
fixes https://github.com/NoelDeMartin/laravel-cypress/issues/9

### CODE REVIEW

**Comment by NoelDeMartin** [comment]
Hi there, thanks for contributing!

This looks good, but I think you are trying to do the following in your tests, right?

```js
cy.artisan('route:list', output => {
    // do something with output here
});
```

I just run this code and this isn't working, you have to adapt the cypress command counterpart as well. You can see that in this other repository: https://github.com/NoelDeMartin/cypress-laravel/blob/master/src/commands.ts#L154 For example, if you compare with the `cy.createUser` command, which does return the user object, it's returning the result of the `cy` calls.

If you are not sure how to do it, let me know and I'll do it myself. I don't think it'd be too difficult.

By the way, I never used `Artisan::output()` but looking at your code I thought it'd return some object given that you want to use it in your test. But it seems like it's just returns a string. Do you mind telling me why do you need this in your tests? I'm curious about the use-case.

**Comment by ianjamieson** [comment]
Ah, yes but I am using it with the `then` chaining like this:

```
cy.artisan('local:command --json').then((output) => {
    console.log(output);
});
```

This seemed to make sense to me to, as this is the same as how you would use a fixture or most other Cypress commands, with the chaining. Happy to implement as you prefer.

I am returning JSON as a string in the command. Like this:


**app/Console/Commands/LocalCommand.php**
```
if($options['json']) {
    $this->info($events);
    return 0;
}
```

It seems as though under the hood, `cy.request` can convert this string to an object.

> Do you mind telling me why do you need this in your tests? I'm curious about the use-case.

Sure, so our website has "events". I am running a command to seed those events. Then I need to be able to visit the URL of the event just seeded. So returning the JSON from that command gives me an object with the URL.

Then I go to that page, I can also expect other data corresponds with the page layout, for example if the event has two tickets, there are two call to action buttons etc. 

I considered using the factories to achieve the above, but we like to abstract out the logic of creating an event to a single command that is reusable.

**Comment by NoelDeMartin** [comment]
Thanks for contributing @ianjamieson! Your changes are available in the latest version of the package :). I've also added an example test to the sandbox project: https://github.com/NoelDeMartin/laravel-cypress-sandbox/commit/0e74dd4fdd2c980409244a7bab39f0fa5f060235

**Comment by ianjamieson** [comment]
Great news, thank you!

**Pull request merged**
